# Fabric https://modmuss50.me/fabric.html

[versions]
lombok-version = "1.18.34"
jetbrains-annotations-version = "26.0.1"
log4j2-version = "2.24.1"

minecraftVersion = "1.21.1"
fabric-loader-version = "0.16.2"
fabric-api-version = "0.102.1+1.21.1"
forge-version = "1.21.1-52.0.4"
neoforge-version = "21.1.22"

# Mod dependencies
modmenu-version = "11.0.3"
curiosVersion = "8.0.2+1.20.6"
trinkets-version = "3.10.0"
cardinal-components-version = "6.1.1"

fabric-loom-version = "1.7+"
forge-plugin-version = "[6.0.24,6.2)"
curse-version = "1.4.0"
modrinth-version = "2.8.7"
names-version = "0.51.0"
git-version-plugin-version = "3.1.0"
neoforge-plugin-version = "7.0.165"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j2-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraftVersion" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-version" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
trinkets = { group = "dev.emi", name = "trinkets", version.ref = "trinkets-version" }
cardinalComponents = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal-components-version" }
curiosneoforge = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curiosVersion" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
curse = { id = "com.matthewprenger.cursegradle", version.ref = "curse-version"}
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth-version"}
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
loom = { id = "fabric-loom", version.ref = "fabric-loom-version" }
forge = { id = "net.minecraftforge.gradle", version.ref = "forge-plugin-version" }
neoforge = { id = "net.neoforged.gradle.userdev", version.ref = "neoforge-plugin-version" }
gitVersion = { id = "com.palantir.git-version", version.ref = "git-version-plugin-version" }
